# -*- coding: utf-8 -*-
"""DentalAppointment_IG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ephgbBdUtrZHP0LRJK5-DrIxIankLPTh
"""

import pandas as pd

df = pd.read_excel('dental_appointments.xlsx')
print(df.shape)
df.head()

df.describe()

df.groupby('Day_of_Week')['No_Show'].mean().round(2) ## converting date to a real date type

df['Appointment_Date'] = pd.to_datetime(df['Appointment_Date'])

monthly = df.set_index('Appointment_Date') \
           .resample('ME')['Appointment_ID'] \
           .count()
print(monthly) ##Group appointments by month and count

##plotting
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))
plt.plot(monthly.index, monthly.values,
         color='steelblue', linewidth=2, marker='o')
plt.title('Monthly Dental Appointments — 2023')
plt.xlabel('Month')
plt.ylabel('Number of Appointments')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('monthly_appointments.png')
plt.show()

##plotting  no show rate
monthly_noshow = df.set_index('Appointment_Date') \
                 .resample('ME')['No_Show'] \
                 .mean()

plt.figure(figsize=(10, 4))
plt.plot(monthly_noshow.index, monthly_noshow.values,
         color='tomato', linewidth=2, marker='o')
plt.title('Monthly No-Show Rate — 2023')
plt.ylabel('No-Show Rate')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

##grouping appts by week instead of month
weekly = df.set_index('Appointment_Date') \
          .resample('W')['No_Show'] \
          .mean()

##calculating a 4-week rolling average
rolling_avg = weekly.rolling(window=4).mean()

##plotting raw weekly data and rolling average together
plt.figure(figsize=(12, 5))

plt.plot(weekly.index, weekly.values,
         color='lightcoral', alpha=0.5,
         linewidth=1, label='Weekly rate')

plt.plot(rolling_avg.index, rolling_avg.values,
         color='darkred', linewidth=2.5,
         label='4-week rolling avg')

plt.title('Weekly No-Show Rate with 4-Week Rolling Average')
plt.ylabel('No-Show Rate')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('rolling_avg_noshow.png')
plt.show()

"""This weekly no show rate fluctuates drastically from week to week, making it chalennging to identify if the clinic's scheduling problem is getting better or worse over time. The 4 week rolling average clears out these short-term spokes and shows a clearer visual pattern, specially when no show rates climb steadily from June to July and August then falling down in the fall. This kind of smoothing is usuel in a clinical setting where a single unsuaul week can maybe distort the visual completely."""